// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBMediator.Models.Admin;

public partial class Cdnsubspec
{
    public int Mkt { get; set; }

    public string Mktname { get; set; }

    public string Version { get; set; }

    public string Subfolder { get; set; }
}