// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBMediator.Models.Admin;

public partial class Maintanenceschedule
{
    public long Uid { get; set; }

    public DateTime Regdate { get; set; }

    public DateTime Startdt { get; set; }

    public DateTime Enddt { get; set; }

    public string Who { get; set; }

    public string Why { get; set; }
}