// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBMediator.Models.AccountDB;

public partial class Accountsessionkey
{
    public long Accidx { get; set; }

    public string Skey { get; set; }
}