// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBMediator.Models.AccountDB;

/// <summary>
/// 유저 플랫폼 링크된 정보
/// 
/// cdtype : 구글, IOS, GUEST 등등
/// acctoken : 구글, IOS, GUEST 등에서 생성된 유저 고유의 토큰
/// </summary>
public partial class Accountcredentiallink
{
    public long Ridx { get; set; }

    public long Accidx { get; set; }

    public int Cdtype { get; set; }

    public string Acctoken { get; set; }

    public DateTime CreationDt { get; set; }

    public DateTime RecentDt { get; set; }
}