// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBMediator.Models.AccountDB;

/// <summary>
/// 게임디비의 샤드정보
/// 
/// - 게임디비들의 샤드정보를 기록
/// - uid : AccountShardDBLink 의 shard_uid 와 매칭
/// </summary>
public partial class ConfigSharddb
{
    public long Uid { get; set; }

    public string Aliasname { get; set; }

    public string Dbcntstring { get; set; }

    public string LogdbCntstring { get; set; }
}